export const PRODUCT_TOOL_CATALOG = [
  {
    name: "capability_search",
    description: "按当前任务搜索 App 能力。最多返回少量摘要,不会把全部 API 定义放入上下文。需要 App 中尚未直接提供为工具的能力时先调用。",
    safety: "read",
    domain: "capability",
  },
  {
    name: "capability_describe",
    description: "读取一个已搜索到的 App 能力详情和输入结构。只加载选中的单个能力,避免污染上下文。",
    safety: "read",
    domain: "capability",
  },
  {
    name: "capability_invoke",
    description: "调用 capability_search 找到的 App 能力。复用当前用户和项目权限;写入操作遵守当前审批模式。",
    safety: "execute",
    domain: "capability",
    confirm: true,
  },
  {
    name: "project_list",
    description: "列出当前用户可访问的问数项目/工作区,可按名称搜索。这是只读基础能力,可在任意工作区用于查看其他工作区。",
    safety: "read",
    domain: "project",
  },
  {
    name: "project_detail",
    description: "查看当前用户可访问的指定问数项目/工作区详情。可按 project_id/id 查看,也可按名称唯一匹配。这是只读基础能力,可在任意工作区使用。",
    safety: "read",
    domain: "project",
  },
  {
    name: "create_smart_qa_project",
    description: "创建新的智能问数项目/工作区,并把当前用户设为项目负责人。仅当用户本轮文本明确要求创建/新建/重建/转成/升级为智能问数项目或工作区时使用;不要从导入、统计或确认卡推导创建。",
    safety: "write",
    domain: "project",
    confirm: true,
  },
  {
    name: "project_create",
    description: "兼容旧名:创建新的智能问数项目/工作区。新流程优先使用 create_smart_qa_project;仅当用户本轮文本明确要求创建/新建/重建/转成/升级为智能问数项目或工作区时使用;不要从导入、统计或确认卡推导创建。",
    safety: "write",
    domain: "project",
    confirm: true,
  },
  {
    name: "project_session_move",
    description: "把当前 Agent 会话迁移到已有、现有、指定或具名问数项目。只能在用户本轮文本明确要求“把当前会话/对话迁移、移动或转到已有或具名问数项目/工作区”时使用;泛泛说转到智能问数应创建新项目,普通文件分析、发票统计、导入数据和确认卡都不能触发。",
    safety: "write",
    domain: "project",
    confirm: true,
  },
  {
    name: "file_classify",
    description: "识别本地文件或目录中的数据文件类型,按数据库文件、结构化文件、非结构化文档分组。",
    safety: "read",
    domain: "file",
  },
  {
    name: "structured_import",
    description: "把 CSV/Excel/JSON/Parquet 等结构化文件导入项目,生成 DuckDB 连接和表字段元数据。",
    safety: "write",
    domain: "structured",
    confirm: true,
  },
  {
    name: "database_file_import",
    description: "把本地 SQLite 或 DuckDB 文件导入项目,创建数据库连接并同步 schema。",
    safety: "write",
    domain: "database",
    confirm: true,
  },
  {
    name: "unstructured_import",
    description: "把 Markdown/PDF/DOCX/TXT 等非结构化文档导入项目知识库,提交后台解析和向量化。",
    safety: "write",
    domain: "unstructured",
    confirm: true,
    long_running: true,
  },
  {
    name: "job_status",
    description: "查询导入、文档解析、schema 同步等数据准备任务的当前状态和摘要。",
    safety: "read",
    domain: "job",
  },
  {
    name: "query_smoke_test",
    description: "对已导入的数据库连接执行轻量只读 smoke test,验证表可查询。",
    safety: "read",
    domain: "query",
  },
  {
    name: "skill_list",
    description: "列出 App 级 Skill Library 中的技能定义。项目上下文中调用时仍然读取 App 级定义。",
    safety: "read",
    domain: "skill",
  },
  {
    name: "skill_create",
    description: "创建 App 级 Skill 定义。不会创建项目私有 Skill;如需当前项目使用,创建后再调用 project_skill_enable。",
    safety: "write",
    domain: "skill",
    confirm: true,
  },
  {
    name: "skill_update",
    description: "更新 App 级自定义 Skill 定义。内置 Skill 不支持编辑定义。",
    safety: "write",
    domain: "skill",
    confirm: true,
  },
  {
    name: "skill_toggle",
    description: "更新 App 级 Skill 总开关或默认启用状态。is_active=false 会让所有项目都不可执行该 Skill。",
    safety: "write",
    domain: "skill",
    confirm: true,
  },
  {
    name: "skill_delete",
    description: "软删除 App 级自定义 Skill 定义。内置 Skill 不可删除。",
    safety: "write",
    domain: "skill",
    confirm: true,
  },
  {
    name: "project_skill_list",
    description: "查看当前或指定问数项目的 effective skills,包括 App 默认状态和项目绑定状态。",
    safety: "read",
    domain: "skill",
  },
  {
    name: "project_skill_enable",
    description: "在当前或指定问数项目中启用一个 App Skill。",
    safety: "write",
    domain: "skill",
    confirm: true,
  },
  {
    name: "project_skill_disable",
    description: "在当前或指定问数项目中禁用一个 App Skill。",
    safety: "write",
    domain: "skill",
    confirm: true,
  },
  {
    name: "mcp_provider_list",
    description: "列出 App 级 MCP Provider Library 中的 Provider 定义。",
    safety: "read",
    domain: "mcp",
  },
  {
    name: "mcp_provider_create",
    description: "创建 App 级 MCP Provider 定义。不会创建项目私有 Provider;如需当前项目使用,创建后再调用 project_mcp_provider_enable。",
    safety: "write",
    domain: "mcp",
    confirm: true,
  },
  {
    name: "mcp_provider_update",
    description: "更新 App 级 MCP Provider 定义,包括 command、args、env 和默认启用状态。",
    safety: "write",
    domain: "mcp",
    confirm: true,
  },
  {
    name: "mcp_provider_toggle",
    description: "更新 App 级 MCP Provider 总开关或默认启用状态。is_active=false 会让所有项目都不可执行该 Provider。",
    safety: "write",
    domain: "mcp",
    confirm: true,
  },
  {
    name: "mcp_provider_delete",
    description: "软删除 App 级 MCP Provider 定义。",
    safety: "write",
    domain: "mcp",
    confirm: true,
  },
  {
    name: "mcp_provider_test",
    description: "用给定 command/args/env 临时连接 MCP Provider 并列出工具。会启动本地命令。",
    safety: "execute",
    domain: "mcp",
    confirm: true,
  },
  {
    name: "mcp_provider_rediscover",
    description: "重新连接 App 级 MCP Provider 并刷新工具发现状态。",
    safety: "execute",
    domain: "mcp",
    confirm: true,
  },
  {
    name: "project_mcp_provider_list",
    description: "查看当前或指定问数项目的 effective MCP Providers,包括 App 默认状态和项目绑定状态。",
    safety: "read",
    domain: "mcp",
  },
  {
    name: "project_mcp_provider_enable",
    description: "在当前或指定问数项目中启用一个 App MCP Provider。",
    safety: "write",
    domain: "mcp",
    confirm: true,
  },
  {
    name: "project_mcp_provider_disable",
    description: "在当前或指定问数项目中禁用一个 App MCP Provider。",
    safety: "write",
    domain: "mcp",
    confirm: true,
  },
  {
    name: "project_mcp_provider_reset",
    description: "清除当前或指定问数项目的 MCP Provider 启用覆盖,恢复继承 App 默认状态。",
    safety: "write",
    domain: "mcp",
    confirm: true,
  },
];

export const PRODUCT_TOOL_NAMES = new Set(PRODUCT_TOOL_CATALOG.map((t) => t.name));
export const PRODUCT_CONFIRM_TOOL_NAMES = new Set(PRODUCT_TOOL_CATALOG.filter((t) => t.confirm).map((t) => t.name));
